const express = require('express')
const fs = require('fs')
const path = require('path')
const router = express.Router()

/**
 * Poly Haven's remote asset library for Blender (5.3+).
 *
 * Blender expects a handful of static JSON files at a root URL, generated by its own
 * `blender -b -c asset_listing generate` and post-processed by blender_asset_repo/publish.py:
 *
 *   /bl_repo/_asset-library-meta.json   the entry point, the only URL Blender knows up front
 *   /bl_repo/_v1/asset-index.json       counts, catalogs, and the page list
 *   /bl_repo/_v1/assets-00000.json      the assets themselves
 *
 * The .blend files and WebP previews they reference are absolute URLs on
 * dl.polyhaven.org (B2, behind the Cloudflare bandwidth alliance) — only this metadata is
 * served from here.
 *
 * Public and unauthenticated: the library is CC0 and Blender ships no token for it.
 *
 * Files are served byte-for-byte as generated, not re-serialised, because the listing embeds a
 * SHA256 of each file and Blender puts it on the query string as a cache-buster. Re-encoding
 * would change the bytes and leave the hash describing something we never send. Loaded once at
 * startup, so publishing a new listing needs a restart (same as taxonomy.json).
 */

const DIR = path.join(__dirname, '..', 'bl_repo')

// Request path -> exact bytes on disk. Built from what's actually there, so no path from the
// request is ever joined onto the filesystem.
const files = {}
const load = (relDir) => {
  for (const name of fs.readdirSync(path.join(DIR, relDir))) {
    const rel = path.posix.join(relDir, name)
    if (fs.statSync(path.join(DIR, rel)).isDirectory()) {
      load(rel)
    } else if (name.endsWith('.json')) {
      files['/' + rel] = fs.readFileSync(path.join(DIR, rel))
    }
  }
}
try {
  load('.')
} catch (err) {
  console.log('bl_repo: could not read', DIR, err.message)
}

// The meta file is the one URL whose content hash can't be in its own URL, so Blender
// cache-busts it with a `?s=<minute-stamp>` instead. Keep its TTL near that resolution;
// everything under _v1 is addressed by `?hash=` and can sit in a cache far longer.
const META = '/_asset-library-meta.json'

router.get('/*', (req, res) => {
  const body = files[req.path === '/' ? META : req.path]
  if (!body) {
    return res.status(404).json({
      error: '404 Not Found',
      message: 'No such asset library file. The library root is /bl_repo/',
    })
  }
  res.set(
    'Cache-Control',
    req.path === META
      ? 'public, max-age=120'
      : 'public, max-age=86400, stale-while-revalidate=604800'
  )
  res.type('application/json').send(body)
})

module.exports = router
