name: Deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy API3
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST_API3}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/api
            git pull
            npm ci
            pm2 restart app --time
      - name: Deploy API5
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST_API5}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/api
            git pull
            npm ci
            pm2 restart app --time
